CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique` (`NAME` ASC)
);

CREATE TABLE IF NOT EXISTS `TV_SHOWS`
(
  `ID`          	BIGINT(20)    NOT NULL AUTO_INCREMENT,
  `NAME` 			VARCHAR(256)  NOT NULL,
  `SHORT_DESC` 		VARCHAR(256)  NULL DEFAULT NULL,
  `LONG_DESC` 		VARCHAR(2048) NULL DEFAULT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `RECOMMENDED_AGE` TINYINT 	  NOT NULL,
  `ADVERTISING` 	VARCHAR(256)  NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `CATEGORY_TV_SHOW`
(
  `CATEGORY_ID`       BIGINT(20)  NOT NULL,
  `TV_SHOW_ID`        BIGINT(20)  NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`, `TV_SHOW_ID`),
  CONSTRAINT `FK_CATEGORY_ID`
    FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (ID),
  CONSTRAINT `FK_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `SEASONS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SEASONS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `CHAPTERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DURATION` 	TINYINT 	 NOT NULL,
  `SEASON_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHAPTERS_SEASON_ID`
    FOREIGN KEY (SEASON_ID) REFERENCES `SEASONS` (ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS `ACTORS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  `SURNAME`  VARCHAR(256) NOT NULL,
  `DATE_BIRTH` 	DATE 	 NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ACTOR_CHAPTER`
(
  `ACTOR_ID`        BIGINT(20)  NOT NULL,
  `CHAPTER_ID`       BIGINT(20)  NOT NULL,

  PRIMARY KEY (`ACTOR_ID`,`CHAPTER_ID`),
  CONSTRAINT `FK_ACTOR_ID`
    FOREIGN KEY (ACTOR_ID) REFERENCES `ACTORS` (ID),
  CONSTRAINT `FK_CHAPTER_ID`
    FOREIGN KEY (CHAPTER_ID) REFERENCES `CHAPTERS` (ID)
);


CREATE TABLE IF NOT EXISTS `AWARDS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DESCRIPTION`  VARCHAR(256) NOT NULL,
  `DATE` 	DATE 	 NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_AWARDS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);


CREATE TABLE IF NOT EXISTS `USERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  `SURNAME`  VARCHAR(256) NOT NULL,
  `USERNAME`  VARCHAR(256) NOT NULL,
  `PASSWORD`  VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`)
);


CREATE TABLE IF NOT EXISTS `ROLES`(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `USER_ROLE`(
  `USER_ID`          BIGINT(20)  NOT NULL,
  `ROLE_ID`       BIGINT(20)  NOT NULL,

  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  CONSTRAINT `FK_USER_ID`
    FOREIGN KEY (USER_ID) REFERENCES `USERS` (ID),
  CONSTRAINT `FK_ROLE_ID`
    FOREIGN KEY (ROLE_ID) REFERENCES `ROLES` (ID)
);